language: node_js
node_js:
  - 12
services:
  - docker
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: build
      script: bash ./build.sh
    - stage: release
      script: bash ./build.sh && bash ./release.sh

stages:
  - lint
  - build
  - name: release
    if: type = push AND branch = master
